name:  MultiSelect
author:  BlazMalezic
current:  1.0
category:  Interface
tags:  [forms, checkbox, dropdown, multi select]
docs:  http://users.skavt.net/bmalezic/MultiSelect
demo:  http://users.skavt.net/bmalezic/MultiSelect/demo