name:  MultiSelect
author:  BlazMalezic
current:  1.3
category:  Forms
tags:  [forms, checkbox, dropdown, multi select, menu]
docs:  http://users.skavt.net/bmalezic/MultiSelect
demo:  http://users.skavt.net/bmalezic/MultiSelect/demo.html